apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: benhelith/keepcoding06:Keepnotes-app
          name: app
          env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: cmdb
                key: dbname
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: cmdb
                key: host
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: userpassword
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          ports:
          - containerPort: 5000
            name: app