# Default values for keepnotes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment
replicaCount: 1
image:
  app: "benhelith/keepcoding06:Keepnotes-app"
  db: "mysql"
  pullPolicy: IfNotPresent

# Service
service:
  type: "LoadBalancer"
  app: 5000
  port: 3306

# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: 34-168-147-24.nip.io
      paths:
      - "/"

# Secret
db:
  rootpassword: rootpassword
  userpassword: keeppass
  username: keepuser

# Configmap
dbname: keepnotes
host: db

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 55


