apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepnotes.fullname" . }}-app
  labels:
    {{- include "keepnotes.labels" . | nindent 4 }}-app
spec:
  ports:
  - port: {{ .Values.service.app }}
    protocol: TCP
    targetPort: 5000
  selector:
    {{- include "keepnotes.selectorLabels" . | nindent 4 }}
    layer: app
  type: {{ .Values.service.type }}
