apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keepnotes.fullname" . }}-mysql-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
