apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepnotes.fullname" . }}-db
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    {{- include "keepnotes.selectorLabels" . | nindent 4 }}
    layer: db
  clusterIP: None
