apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keepnotes.fullname" . }}-secret
type: Opaque
data:
  rootpassword: {{ .Values.db.rootpassword | b64enc | quote }}
  userpassword: {{ .Values.db.userpassword | b64enc | quote }}
  username: {{ .Values.db.username | b64enc | quote }}
